aa: rand-m9-mstd0.5-inc1
amp: true
batch_size: 256
cfg: /home/lan/zqq/autoFormer/experiments/subnet/evolution_dss_t.yaml
change_qkv: true
clip_grad: null
color_jitter: 0.4
cooldown_epochs: 10
cutmix: 1.0
cutmix_minmax: null
data_path: /home/lan/zqq/imagenet/
data_set: IMNET
decay_epochs: 30
decay_rate: 0.1
device: cuda
dist_backend: nccl
dist_eval: true
dist_url: tcp://localhost:2041
distributed: true
drop: 0.0
drop_block: null
drop_path: 0.1
epochs: 300
eval: false
gp: true
gpu: 0
inat_category: name
input_size: 224
lr: 0.0005
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
lr_power: 1.0
max_relative_position: 14
min_lr: 1.0e-05
mixup: 0.8
mixup_mode: batch
mixup_prob: 1.0
mixup_switch_prob: 0.5
mode: retrain
model: ''
model_ema: false
model_ema_decay: 0.99996
model_ema_force_cpu: false
momentum: 0.9
no_abs_pos: false
num_workers: 10
opt: adamw
opt_betas: null
opt_eps: 1.0e-08
output_dir: ''
patch_size: 16
patience_epochs: 10
pin_mem: true
platform: pai
post_norm: false
rank: 0
recount: 1
relative_position: true
remode: pixel
repeated_aug: true
reprob: 0.25
resplit: false
resume: /home/lan/zqq/autoFormer/outputs/evolution_dss_t/checkpoint.pth
rpe_type: bias
sched: cosine
seed: 0
smoothing: 0.1
start_epoch: 0
teacher_model: ''
train_interpolation: bicubic
warmup_epochs: 10
warmup_lr: 1.0e-06
weight_decay: 0.05
world_size: 1
